### PR TITLE
Updated below things including UNSAFE_componentWillMount warning

### PR DESCRIPTION
**Pull request by velusgautam**
1. flowconfig Updated for Travis CICD
2. UNSAFE_componentWillMount for React Upgrade
3. Added package-lock.json

### CODE REVIEW

**Comment by velusgautam** [comment]
@jamiebuilds Can you please verify this PR
I update the **yarn.lock** file since it was throwing error in travis builds
Changed travis.yml to build only for **node 8 and 10**
update .flowconfig path to ignore **chalk**

**Comment by fgiarritiello** [comment]
Can we please merge this?

**Comment by masad-frost** [comment]
Seems like the maintainer of this Repo lost all interest in it (He's busy fighting for the justice of the minority groups). I recommend forking it.

**Comment by kopax** [comment]
Hello, this is really needed here for many people. Is this still maintained ?

**Comment by masad-frost** [comment]
@kopax use loadable/components, or fork this library

**Comment by kopax** [comment]
is it the same API?

**Comment by kopax** [comment]
@masad-frost those libraries are different. They do not provide the sames features. Did anybody fork and release on npm the fix?

**Comment by lovewinders** [comment]
#### react-loadable Loadable.Capture report is not support ssr?
// App.tsx
```
import React from 'react';
import {Route, Redirect, withRouter, Switch} from 'react-router-dom';
import Loadable from 'react-loadable';
import Loading from 'app/components/Loading';

const LoadableTab=Loadable({
  loader: () => import(/* webpackChunkName: 'Tab' */ './A'),
// typescript is not auto insert webpack/modules
//   webpack: () => [require.resolveWeak('./A')],
//   modules: ['./A'],
  loading:Loading
});
const LoadableUser = Loadable({
  loader: () => import(/* webpackChunkName: 'User' */ './B'),
//   webpack: () => [require.resolveWeak('./B')],
//   modules: ['./B'],
  loading:Loading
});

class App extends React.Component{
	render(){
		return(
			<React.Fragment>
				<Switch>
					<Route path="/login"  component={LoadableTab}/>
					<Route path="/join"  component={LoadableUser}/>
					<Route path="/"  component={LoadableUser}/>
				</Switch>
				<LoadableUser />
			</React.Fragment>
			)
	}
};

export default App;
```

// index.js
```
import App from "App.tsx";
...
const rootString = renderToString(
        <Loadable.Capture
            report={moduleName => {
                console.log('============If App is tsx/ts, Not executed here============>>>>>>>', moduleName)
                return modules.push(moduleName)
            }}
        >
            <Provider store={store}>
                <StaticRouter location={ctx.req.url} context={context}>
                    <App/>
                </StaticRouter>
            </Provider>
        </Loadable.Capture>
    );
```
so this moduleName is Empty array

**Comment by shehi** [comment]
Now please let's have a release :)

**Comment by velusgautam** [comment]
@kopax flow issues are fixed in this pull request. You can refer the changed files

**Comment by KorySchneider** [comment]
Would love for this to get merged, using fork from @kopax in the meantime

**Comment by velusgautam** [comment]
React Loadable implementation with React 17.0.1.  🎉

https://www.npmjs.com/package/react-loadable-hooks

**Comment by shehi** [comment]
> React Loadable implementation with React 17.0.1. 🎉
> 
> https://www.npmjs.com/package/react-loadable-hooks

It looks like you "forked" this repo (since a lot of its pieces are from this one), but at the same time stripped the git history of it, making zero initial commit. Why not do proper forking, at the same time respecting the previous work done here?!

And you are violating the following clause of MIT license (as you removed the LICENSE file from your repo):
>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by shehi** [comment]
> React Loadable implementation with React 17.0.1. 🎉
> 
> https://www.npmjs.com/package/react-loadable-hooks

And you are following clause of MIT license (as you removed the LICENSE file from your repo):
>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by velusgautam** [comment]
> > React Loadable implementation with React 17.0.1. 🎉
> > https://www.npmjs.com/package/react-loadable-hooks
> 
> It looks like you "forked" this repo (since a lot of its pieces are from this one), but at the same time stripped the git history of it, making zero initial commit. Why not do proper forking, at the same time respecting the previous work done here?!
> 
> And you are violating the following clause of MIT license (as you removed the LICENSE file from your repo):
> 
> > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
@shehi Thanks for pointing. 
Added license and history. 

And I already have a forked version and created this Pull Request. And the other has more changes and cant be merged to this, that's why I added that to a new repo

**Comment by shehi** [comment]
> > > React Loadable implementation with React 17.0.1. 🎉
> > > https://www.npmjs.com/package/react-loadable-hooks
> > 
> > 
> > It looks like you "forked" this repo (since a lot of its pieces are from this one), but at the same time stripped the git history of it, making zero initial commit. Why not do proper forking, at the same time respecting the previous work done here?!
> > And you are violating the following clause of MIT license (as you removed the LICENSE file from your repo):
> > > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
> > > @shehi Thanks for pointing.
> > > Added license and history.
> 
> And I already have a forked version and created this Pull Request. And the other has more changes and cant be merged to this, that's why I added that to a new repo

Then please apply your changes to existing latest version of this package? I for sure won't be using a new package, when its author decided not to bother with proper PR and conflict management. As I said, making clean slate repo with no git history whatsoever is just blunt plagiarism in my book. This will be my last comment on this topic. Have a nice day!

**Comment by LukeXF** [comment]
Please can we get an update on this?

**Comment by slorber** [comment]
For anyone interested, here's my solution to get rid of the warning (React 16 + 17) and still get this working (client+SSR).

https://github.com/jamiebuilds/react-loadable/pull/213#issuecomment-778246548

**Comment by qq281113270** [comment]
> 1. flowconfig Updated for Travis CICD
> 2. UNSAFE_componentWillMount for React Upgrade
> 3. Added package-lock.json

This author doesn't seem to be updating this component, but you can look at similar components that implement SSR PROMISE asynchronous loading，github address ：https://github.com/qq281113270/react-lazy-router-dom

**Comment by fangyinghua** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Pull request closed without merging**
