### PR TITLE
Migrate to webpack@4 API

### PR DESCRIPTION
**Pull request by 7rulnik**

### CODE REVIEW

**Comment by nandosangenetto** [comment]
Hey @7rulnik, thank you for the update!

I've got this error when I tried to compile with Webpack:
```> webpack-cli --mode production

/Users/user/my_side/node_modules/webpack-cli/bin/webpack.js:237
                                throw err;
                                ^

Error: Cannot find module './lib/webpack'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (/Users/user/my_side/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/user/my_side/node_modules/react-loadable/webpack.js:1:80)
    at Module._compile (/Users/user/my_side/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (/Users/user/my_side/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/user/my_side/webpack.config.js:6:33)
    at Module._compile (/Users/user/my_side/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (/Users/user/my_side/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/user/my_side/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Users/user/my_side/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /Users/user/my_side/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/user/my_side/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/Users/user/my_side/node_modules/webpack-cli/bin/webpack.js:234:39)
    at Object.parse (/Users/user/my_side/node_modules/yargs/yargs.js:539:18)
    at /Users/user/my_side/node_modules/webpack-cli/bin/webpack.js:212:8
    at Object.<anonymous> (/Users/user/my_side/node_modules/webpack-cli/bin/webpack.js:504:3)
    at Module._compile (module.js:660:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1```

**Comment by joacub** [comment]
in webpack 4 all import() is wrapped in default, need change code in render of object assign to return obj.default

**Comment by joacub** [comment]
`function render(loaded, props) {
const resolved = resolve(loaded);
const component = Object.prototype.hasOwnProperty.call(resolved, 'default') ? resolved.default : resolved;
  return React.createElement(resolve(loaded), props);
}`

this resolve the problem when use import for loading the components

**Comment by 7rulnik** [comment]
@nandosangenetto seems that you forget to transpile files.

@joacub nice catch! Can you give some more info about `js await trigger('fetch', components, triggerLocals)`?

**Comment by bertho-zero** [comment]
Instead of `hasOwnProperty` on the default property, you can use something like:

```js
const component = resolved && resolved.__esModule ? resolved.default : resolved;
```

**Comment by Obooman** [comment]
Waiting for the further merge operation

**Comment by joacub** [comment]
@7rulnik trigger fetch running before correct and running ok if in the import use a .then(object => object.default)

**Comment by Oza94** [comment]
@7rulnik ,

Is there an estimated timeline for this PR to land ? We're waiting it in order to move to webpack 4.

Sorry to ask the question here, I understand this may not be the right place but since issues are not enabled /accessible 😅 

By the way thanks to all `react-loadable` contributors this is really awesome 👍

**Comment by 7rulnik** [comment]
@Oza94

**Comment by Oza94** [comment]
Thanks for the feedback @7rulnik :)

The scoped package is a good option for us, at least we can validate that everything works fine. However we can also wait a few days for the main package and @jamiebuilds 's response so do not feel committed to publish it

**Comment by 7rulnik** [comment]
@Oza94 just published https://yarnpkg.com/en/package/@7rulnik/react-loadable
Feel free to test it.

**Comment by onetrickwolf** [comment]
@7rulnik tried using your release but am getting `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

If I downgrade to Webpack 3 everything works as expected. Any ideas? Been debugging for awhile.

**Comment by 7rulnik** [comment]
@onetrickwolf did you saw https://github.com/jamiebuilds/react-loadable/pull/110#issuecomment-371013933?

Are you using es6 modules or commonJS?

**Comment by onetrickwolf** [comment]
@7rulnik hey sorry should have read better, thanks that fixed it. For others having the same problem this fixed it for me:

```const Loading = () => <div>Loading...</div>;

const myComponent = Loadable({
  loader: () => import('./myComponent.react').then(object => object.default),
  loading: Loading,
});
```

Will this be the permanent fix by the way? Should the docs be updated once this PR is merged?

**Comment by joacub** [comment]
@onetrickwolf yes, aparently this is the way, webpack in the import return always object { default }, this not is catcheable for react-loadable.

**Comment by alamchrstn** [comment]
can I confirm is the current master version of react-loadable compatible with webpack 4 out of the box? Sorry still newbie here 🙇

**Comment by EvHaus** [comment]
@alamchrstn It works, but there are bugs with HMR. For me, builds will randomly start to throw `Unhandled rejection TypeError: Cannot read property 'call' of undefined` from components that use `react-loadable` and the only way I've found to recover is to restart the webpack server.

**Comment by EvgeniyKumachev** [comment]
@alamchrstn I don't think current master version supports webpack 4, that's why this pull is still open

**Comment by alamchrstn** [comment]
@EvgeniyKumachev ah I see, can someone give a working example of react loadable with webpack 4? thanks in advance 🙇 I'm still learning here...

**Comment by 7rulnik** [comment]
@alamchrstn you can use https://github.com/jamiebuilds/react-loadable/pull/110#issuecomment-373516381

**Comment by Bram-Zijp** [comment]
How do you guys setup the splitchunks configuration?

**Comment by joacub** [comment]
I’m working dame only change de load method for this
`
const myComponent = Loadable({
  loader: () => import('./myComponent.react').then(object => object.default),
  loading: Loading,
});
`

**Comment by dekryptic** [comment]
How do you handle `vendors-XXX.bundle.js` files?

**Comment by 7rulnik** [comment]
@dekryptic 
I faced this problem yesterday. I have idea how to fix it, but seems that it will be breaking change.

**Comment by dekryptic** [comment]
@joacub Can you show how they are loaded?

**Comment by dekryptic** [comment]
@7rulnik Do you have a working version up? If not, how do you suggest it be handled?

**Comment by abram-zhao** [comment]
@7rulnik You didn't change this
```javascript
 var source = path.node.source.value;
 if (source !== 'react-loadable') return;
```
 at lib/babel.js line 13. In your scoped package so the babel plugin didn't work. The source should be `@7rulnik/react-loadable`. Otherwise this it will always return.
@jamiebuilds Did you have any plan to merge this PR? This will solve so many problems if we are using webpack v4.

**Comment by abramstyle** [comment]
@7rulnik You didn't change this
```javascript
 var source = path.node.source.value;
 if (source !== 'react-loadable') return;
```
 at lib/babel.js line 13. In your scoped package the babel plugin didn't work. The source should be `@7rulnik/react-loadable`. Otherwise this it will always return.
@jamiebuilds Did you have any plan to merge this PR? This will solve so many problems if we are using webpack v4.

**Comment by ankibalyan** [comment]
I'm getting this warning in `webpack 4.5`, and `react 16.3`

```
    Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op.

    Please check the code for the LoadableComponent component.
```

**Comment by ankibalyan** [comment]
Shall I  create a PR supporting new lifecycle for 16.3? it shouldt coming to @next version of `react-loadable`?

**Comment by 7rulnik** [comment]
@abramstyle just published @7rulnik/react-loadable@5.3.3

**Comment by 7rulnik** [comment]
Manifest now contains all vendors chunks. And it's smaller.
Also I added `chunkName` options. It's useful for [webpack-flush-chunks](https://github.com/faceyspacey/webpack-flush-chunks).

**Comment by Bram-Zijp** [comment]
@VincentCharpentier 
I'm currently using `@7rulnik/react-loadable@5.3.4` and it's working fine.

`react-loadable.json`
```
{
  "./TodoContainer": [
    {
      "file": "0.js",
      "publicPath": "/build/0.js",
      "chunkName": null,
      "id": "./src/client/pages/todo/TodoContainer.jsx",
      "name": "./src/client/pages/todo/TodoContainer.jsx"
    }
  ],
...
```

**Comment by VincentCharpentier** [comment]
Thank you for the feedback, I'll try to find out was I'm missing

**Comment by VincentCharpentier** [comment]
I was using `dynamic-import-webpack` before, should I replace it with `dynamic-import-node` ?

**Comment by dgeibi** [comment]
webpack 4 can handle dynamic import. just use `@babel/plugin-syntax-dynamic-import`

**Comment by Bram-Zijp** [comment]
@VincentCharpentier Sounds like you didn't add *@7rulnik* everywhere and are still using react-loadable. Do a search for react-loadable in your project. Make sure every definition is prefixxed like so: `@7rulnik/react-loadable`. I'm guessing you forgot to add it in your `.babelrc` or babel config inside webpack.

**Comment by VincentCharpentier** [comment]
I don't have react-loadable installed, only `@7rulnik/react-loadable` while this PR is not merged. I searched anyway but with no luck.
My babel+webpack config is like this: 

```javascript
module: {
    rules: [
      {
        test: /\.(js|jsx)?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            babelrc: false,
            plugins: [
              '@7rulnik/react-loadable/babel',
              'syntax-dynamic-import',
            ],
            presets: [
              [
                'env',
                {
                  'loose': false,
                  'shippedProposals': true,
                },
              ],
              'react',
            ],
          },
        },
      },
      // ...
```

and my .babelrc (for server):
```json
// server only
{
  "plugins": [
    "@7rulnik/react-loadable/babel",
    "dynamic-import-node"
  ],
  "presets": [
    [
      "env",
      {
        "loose": false,
        "shippedProposals": true
      }
    ],
    "react"
  ]
}
```

Only difference between them is `dynamic-import-node` vs. `syntax-dynamic-import`

**Comment by VincentCharpentier** [comment]
thanks for your feedback. Could you also share you package.json ? especially dependencies and devdependencies, I think I have something incompatible

**Comment by Bram-Zijp** [comment]
```
  "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.3",
    "babel-jest": "^22.4.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-direct-import": "^0.5.0",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-plugin-lodash": "^3.3.2",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "react-hot-loader": "^4.0.1",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.14",
    "@7rulnik/react-loadable": "^5.3.4",
```

**Comment by VincentCharpentier** [comment]
Thanks for your feedback.
I found out what was messing things up. I'm using a component like this:

```
import L from '@7rulnik/react-loadable';
import Loading from '../components/Loading';

function Loadable (opts) {
  return L(Object.assign({}, {
    loading: Loading,
  }, opts));
}
```

Then I can only provide loader property when I want to use Loadable.
This is inspired by https://twitter.com/matzatorski/status/872059865350406144 (first link README.md > happy customers)

In this scenario, react-loadable is now broken 😕. It won't generate ids in the manifest, thus breaking the SSR (no module reported)

**Comment by steplov** [comment]
@7rulnik Hello, thank you for you fork. I found the issue with webpack plugin. In some cases block.module is null https://github.com/7rulnik/react-loadable/blob/scoped-version/src/webpack.js#L26 and plugin obviously throws the error. Could you please add small check that module object exists?

**Comment by vasivas** [comment]
> Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op.
> 
> Please check the code for the LoadableComponent component.
> 

? :confused:

**Comment by ankibalyan** [comment]
@vasivas This is because `react v16.3` has depricated `componentWillMount` lifecycle method, and `react-loadable` is using it, so a warning message.

**Pull request closed without merging**
