### PR TITLE
Add GermanTechJobs.de to the user list

### PR DESCRIPTION
**Pull request by Vrq**
Hi, we are also using react-loadable - it helped us split our giant bundle into manageable chunks 😄

### CODE REVIEW

**Comment by cweekly** [comment]
DUP w #236?

**Comment by Vrq** [comment]
@cweekly it's the same frontend engine but different sites :)
up to you :)

**Comment by hustcer** [comment]
@jamiebuilds Could you make `react-loadable` support webpack 5? Please. Thank you!

**Comment by Vrq** [comment]
@jamiebuilds all green, could you please merge it? 😃

**Comment by Vrq** [comment]
@jamiebuilds any comments? 👍 👎

**Comment by Vrq** [comment]
@jamiebuilds would you mind merging this PR?

**Comment by Vrq** [comment]
@jamiebuilds could you please merge this PR?

**Comment by Vrq** [comment]
@jamiebuilds could you please merge this PR?

**Pull request closed without merging**
