### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aichnerc**
My company has been added to the user-list.

### CODE REVIEW

**Comment by jamiebuilds** [comment]
I don't really want to have individuals on this list

**Comment by Aichnerc** [comment]
This is my company, with multiple people being employed.

**Comment by jamiebuilds** [comment]
Yeah, but it is named after you using your full name, making it sound like a personal endorsement, which I am uncomfortable with.

**Comment by Aichnerc** [comment]
Alright. Your project, your choice.

**Pull request closed without merging**
