### PR TITLE
Upgrade Babel 7

### PR DESCRIPTION
**Pull request by isacjunior**
## Babel 7 Released
https://babeljs.io/blog/2018/08/27/7.0.0

Drop support for un-maintained Node versions: 0.10, 0.12, 4, 5 ([details](http://babeljs.io/blog/2017/09/12/planning-for-7.0#drop-support-for-unmaintained-node-versions-010-012-5-4315-https-githubcom-babel-babel-issues-4315))

### CODE REVIEW

**Comment by turbothinh** [comment]
Do we have any timeframe to merge this request yet?

**Comment by stephenway** [comment]
```js
WARNING in ./src/chalkApp/screens/AppRoutes.js 59:30-38
"export 'Loadable' was not found in 'react-loadable'
 @ ./src/chalkApp/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/chalkApp/index.js
```

I'm running into this roadblock using Babel 7 and would like to get support.

**Comment by mohsinulhaq** [comment]
this repo has been abandoned it seems.
ser @jamiebuilds is upset with all of us.

**Comment by isacjunior** [comment]
@jamiebuilds Can you merge this PR? Is there a problem that I can help?

**Comment by ThamosIO** [comment]
Hi @jamiebuilds, I'd also love to see this PR merged 🙏  Any idea when you might merge it ?

**Comment by jaybe78** [comment]
Lots of PR have not been merged and the owner of the project does not seem to respond.
Has this project been abandoned ?

**Comment by jaybe78** [comment]
k

**Comment by mohsinulhaq** [comment]
ser @jamiebuilds has not been active on this repository after the ICE thing

**Comment by mohsinulhaq** [comment]
I am also not able to view issues page

**Comment by mohsinulhaq** [comment]
k

**Comment by jaybe78** [comment]
@mohsinulhaq 
What is the ICE thing ?
Anyway there's a lot of important PR that are waiting to be merged, and I'm really interested in using that lib for my next project.
So, I'm thinking about forking the project cloning in it in a new repo and merging all the PR that are waiting like the upgrade to babel 7 and the fix for webpack 4.

**Comment by mohsinulhaq** [comment]
https://github.com/jamiebuilds/react-loadable/commit/c3272b3132e4fe25937c3610b7cd0dd2da48c5e9
which was later reverted after backlash

**Comment by jaybe78** [comment]
@mohsinulhaq 
Ok so basically there won't be any work done on the project anymore unless we revive it

**Comment by mohsinulhaq** [comment]
i don't know, let's tweet to him...he's active there

**Comment by jaybe78** [comment]
I've forked and merged following PRs on my repo if anyone is interested:
[jamiebuilds#151 Upgrade Babel 7
[jamiebuilds#136 Switched to using two layers of .default to workaround a webpack/node bug
[jamiebuilds#127 Migrate from legacy to new React lifecycle
[https://github.com/jamiebuilds/react-loadable/pull/110/files Migrate to webpack 4
[jamiebuilds#132 Use webpack asset system instead of manually writing file
[jamiebuilds#159 throw error instead of update

https://github.com/jaybe78/react-loadable

**Comment by mohsinulhaq** [comment]
Great! Do you plan to maintain this fork?

**Comment by jaybe78** [comment]
@mohsinulhaq I do!

**Comment by jaybe78** [comment]
@mohsinulhaq @isacjunior @ThamosIO 
You've probably forked the project already to migrate to babel 7 but if not
please check this out https://www.npmjs.com/package/jaybe-react-loadable
Cheers

**Comment by jaybe78** [comment]
@VincentCharpentier 
#140 has been merged also.
React 16.6.0 has just been released today which includes lazy loading.
It does not support SSR yet though
https://reactjs.org/blog/2018/10/23/react-v-16-6.html

**Comment by squibbleFish** [comment]
@jaybe78 did you publish your fork to npm?

**Comment by aleehedl** [comment]
Any news on this? @jamiebuilds. 

I managed to succesfully use the fork by @isacjunior in my project, but installing from github via npm is not an option in production. Is @jaybe78 planning to publish to npm?

**Comment by VincentCharpentier** [comment]
jamiebuilds is no longer active on this repo.

take a look at the thread, jaybe has already given the link to his npm package
https://www.npmjs.com/package/jaybe-react-loadable

**Comment by isacjunior** [comment]
@aleehedl You need to use code splitting in server side? If not, I recommend using `lazy` with React. https://reactjs.org/docs/code-splitting.html#reactlazy

**Comment by VincentCharpentier** [comment]
loadable-components is also nice and SSR ready
https://github.com/smooth-code/loadable-components

**Pull request merged**
